# Full crawl configuration with multiple seed URLs
# depth: 3  # Comment out for unlimited depth
delay: 1.0  # 1 second delay between requests
obey_robots: true
strict_domain: true  # Only follow URLs ending with lib.uiowa.edu

# Target domains
domains:
  - lib.uiowa.edu

# Multiple seed URLs to ensure comprehensive coverage
start_urls:
  - https://www.lib.uiowa.edu
  - https://blog.lib.uiowa.edu
  - https://guides.lib.uiowa.edu
  - https://pubs.lib.uiowa.edu
  - https://aspace.lib.uiowa.edu
  - https://ask.lib.uiowa.edu
  - https://diyhistory.lib.uiowa.edu
  - https://library.law.uiowa.edu
  - https://scpatron.lib.uiowa.edu
  - https://digital.lib.uiowa.edu
